### ISSUE TITLE
Contributor installation instructions broken

### ISSUE THREAD

**Issue by sherbold** [cblearn/cblearn#66]
The URL in the contributor installation instructions is broken and needs to be changed to: git@github.com:cblearn/cblearn.git

(cc https://github.com/openjournals/joss-reviews/issues/6139)

**Comment by haniyeka** [comment]
I was going to mention the same as a minor issue. Thanks for bringing that up.

**Comment by dekuenstle** [comment]
Should be fixed now in the latest release: https://github.com/cblearn/cblearn/releases/tag/0.2.0
