### ISSUE TITLE
r_wrapper installation instructions missing

### ISSUE THREAD

**Issue by sherbold** [cblearn/cblearn#67]
The ordinal embedding example cannot be executed without the r_wrapper. The installation for this is not documented and does not work out-of-the-box on a clean Ubuntu 22.04. 

In general, there should be transparency for which features the r-wrapper is required, as well as further information what needs to be installed prior to calling `pip install cblearn[r_wrapper]`. 

(cc https://github.com/openjournals/joss-reviews/issues/6139)

**Comment by dekuenstle** [comment]
Should be fixed in the latest release: https://github.com/cblearn/cblearn/releases/tag/0.2.0
