### ISSUE TITLE
Bug with estimate_dimensionality_cv

### ISSUE THREAD

**Issue by Vivdaddy** [cblearn/cblearn#71]
Hi, 

There seems to be a bug in the embedding.estimate_dimensionality_cv function. (Using current version 706bfba8889799b269a73d2729a38a976e47f6db)

The issue seems to be an issue in the initialization of the embedding. It happens for both SOE and TSTE. 

Here is a basic working example.

```
import cblearn
from cblearn.embedding import SOE
from cblearn.embedding import TSTE
from cblearn.embedding import estimate_dimensionality_cv
from cblearn.datasets import make_random_triplet_indices, make_all_triplet_indices, triplet_response, noisy_triplet_response
import numpy as np

SUBSPACE_DIM = 5
SPACE_DIM = 10
EMBEDDING_DIM = 5
SEED = 42
NUM_TASKS = 25

noisy_points = np.random.randn(NUM_TASKS, SPACE_DIM)
triplets = make_all_triplet_indices(NUM_TASKS, True)
responses = triplet_response(triplets, noisy_points)
estimator = SOE(EMBEDDING_DIM, random_state=SEED)
# Even the following line doesn't work
#estimator = TSTE(EMBEDDING_DIM, random_state=SEED)
dimension = estimate_dimensionality_cv(estimator, responses, test_dimensions=list(range(10)), n_splits=10, n_repeats=1, n_jobs=1, random_state=SEED)
dimension.plot_scores()
```

The error I get is 
![error](https://github.com/cblearn/cblearn/assets/37226693/5a8f3649-f4d5-472b-b031-5159374c2fab)

**Comment by dekuenstle** [comment]
Thank you for sharing the problem. It is not a bug but failing intentionally: You are trying to estimate an embedding with dimension 0. I admit that the error message is not helpful, and I will improve it in future versions.

To fix it in your example, `test_dimensions=list(range(10))` should become `test_dimensions=list(range(1, 11))`.
Note that by testing 10 dimensions, the test power is reduced a lot (multiple testing corrections).
